# Site settings
title: Movies for you
email: gentle3350@naver.com
url: https://gentle9610.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 633160
  secondary: 10bc2b 
  secondary-dark: 9b5e40  

# Footer settings
footer:
  copyright: 15년도1학기 컴퓨터기초설계 2분반 7조
  location: Koreatech
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 충청남도 천안시 동남구
  - line: 가전리 병천면 한국기술교육대

# Credits content
credits: '2015.1 컴시설 2-7조</a>.'

# Build settings
markdown: kramdown
permalink: pretty
